### PR TITLE
fix ambiguous ContravariantShow[SortedSet[A]] (& SortedMap)

### LINKED ISSUE #4574: ambiguous implicit resolution of `Show.ContravariantShow[immutable.SortedMap[K, V]]`
In the following code:

```scala
object ShowIssue {

  val ok = Show[SortedMap[Int, String]]
  val ko = implicitly[Show.ContravariantShow[SortedMap[Int, String]]]

}
```

the line `val ko = ...` fails to compile with:

> ambiguous implicit values:
>   both method catsShowForMap in object Show of type [K, V](implicit evidence$9: cats.Show[K], evidence$10: cats.Show[V]): cats.Show[Map[K,V]]
>   and method catsShowForSortedMap in object Show of type [K, V](implicit evidence$12: cats.Show[K], evidence$13: cats.Show[V]): cats.Show[scala.collection.immutable.SortedMap[K,V]]
>   match expected type cats.Show.ContravariantShow[scala.collection.immutable.SortedMap[Int,String]]
>    val ko = implicitly[Show.ContravariantShow[SortedMap[Int, String]]]

This is rarely an issue in practice (just use the Show instance), except when a library attempts to specifically summon a ContravariantShow instance, such as kittens apparently does (since 3.1.0 I believe)

Seen with cats-core 2.10.0, under Scala 2.13.13

Thank you for your consideration

### PR DESCRIPTION
**Pull request by chwthewke**
Fixes #4574 (I hope...)

### CODE REVIEW

File: core/src/main/scala/cats/Show.scala [hunk 1]
```diff
@@ -120,6 +117,10 @@ object Show extends ScalaVersionSpecificShowInstances with ShowInstances {
 private[cats] trait ShowInstances extends cats.instances.NTupleShowInstances with ShowInstances0 {
   implicit def catsShowForFiniteDuration: Show[FiniteDuration] =
     cats.instances.finiteDuration.catsStdShowForFiniteDurationUnambiguous
+
+  implicit def catsShowForSortedSet[A: Show]: Show[SortedSet[A]] = cats.instances.sortedSet.catsStdShowForSortedSet[A]
+  implicit def catsShowForSortedMap[K: Show, V: Show]: Show[SortedMap[K, V]] =
+    cats.instances.sortedMap.catsStdShowForSortedMap[K, V]
```
Comment (joroKr21) [inline core/src/main/scala/cats/Show.scala:123]: It looks like now `Show` will be ambiguous. What if we move `catsShowForSet` and `catsShowForMap` up instead? Does it work?

Comment (joroKr21) [reply core/src/main/scala/cats/Show.scala:123]: Also adding a test would be great (well not really a test, just summon the instance in test code - I think if you look for it there are places that test summoning some instance compiles).

Comment (chwthewke) [reply core/src/main/scala/cats/Show.scala:123]: I'm not seeing an error trying to summon, e.g. `Show[SortedMap[Int, String]]` with this patch. Should I be looking at another test case?

Comment (chwthewke) [reply core/src/main/scala/cats/Show.scala:123]: Also, I did not write that anywhere, but my change was largely motivated by the observation that Duration and FiniteDuration are like that and their implicits are OK

Comment (joroKr21) [reply core/src/main/scala/cats/Show.scala:123]: Oh, my bad - you're right. The rule goes like this:
```scala
class DefinesA { implicit a: A }
class DefinesB { implicit b: B }
```

* if `A <:< B` then `a` gets a point in the implicit score
* if `DefinesB` <:< `DefinesA` then `b` gets a point in the implicit score
* so both would be 1:1 so ambiguous

However, `Show[SortedSet[A]]` is **not** a subtype of `Show[Set[A]]` because `Show` is invariant.
It just looked similar to issues we've had in the past like this one: #4569

Comment (joroKr21) [reply core/src/main/scala/cats/Show.scala:123]: But this makes me think that it will pick the wrong instance for `SortedSet` and `SortedMap` - I guess that warrants adding a unit test.

Comment (joroKr21) [reply core/src/main/scala/cats/Show.scala:123]: Also `BitSet` has the same issue

Comment (chwthewke) [reply core/src/main/scala/cats/Show.scala:123]: > But this makes me think that it will pick the wrong instance for `SortedSet` and `SortedMap` - I guess that warrants adding a unit test.

It does seem to be the case (for implicitly[ContravariantShow[...]], since as you noted Show[...] cannot have that problem, being invariant).

I'll look into it more when I can, hopefully before Monday.

Comment (joroKr21) [reply core/src/main/scala/cats/Show.scala:123]: The relationship between `SortedSet` and `Set` is the same as `List` and `Seq`, e.g.
And the instance for `Seq` is even further down, so the opposite - we moved `Seq`, not `List`

**Comment by chwthewke** [comment]
Some good news: I've added tests fot `ContravariantShow` implicit resolution and `show` interpolation for `Set`/`SortedSet`/`BitSet` and `Map`/`SortedMap`, and they look good to me (the solution was indeed to pull the superclass instances into parent traits and not the reverse).

Some less good news but it's okay, kinda: `Duration`/`FiniteDuration` have the same problem, where `implicitly[Show.ContravariantShow[FiniteDuration]]` pulls the `Show[Duration]` instance, and I've exhausted my (limited) bag of tricks (including moving stuff along the trait hierarchy and adding dummy value parameters) trying to make it not do that. On the other hand, the implementation of both `Show[FiniteDuration]` and `Show[Duration]` is `Show.fromToString`, so the "incorrect" instance behaves identically to the correct one. Although I feel it's a teeny tiny bit brittle to rely on that fact, there should never be an issue in practice.

File: core/src/main/scala/cats/Show.scala [hunk 2]
```diff
@@ -120,8 +117,12 @@ object Show extends ScalaVersionSpecificShowInstances with ShowInstances {
 private[cats] trait ShowInstances extends cats.instances.NTupleShowInstances with ShowInstances0 {
   implicit def catsShowForFiniteDuration: Show[FiniteDuration] =
     cats.instances.finiteDuration.catsStdShowForFiniteDurationUnambiguous
+
+  implicit def catsShowForSortedSet[A: Show]: Show[SortedSet[A]] = cats.instances.sortedSet.catsStdShowForSortedSet[A]
```
Comment (joroKr21) [inline core/src/main/scala/cats/Show.scala:121]: This could've stayed in the old position

**Review by joroKr21 — APPROVED** [review]

**Comment by joroKr21** [comment]
> Some less good news but it's okay, kinda: Duration/FiniteDuration have the same problem, where implicitly[Show.ContravariantShow[FiniteDuration]] pulls the Show[Duration] instance, and I've exhausted my (limited) bag of tricks (including moving stuff along the trait hierarchy and adding dummy value parameters) trying to make it not do that. On the other hand, the implementation of both Show[FiniteDuration] and Show[Duration] is Show.fromToString, so the "incorrect" instance behaves identically to the correct one. Although I feel it's a teeny tiny bit brittle to rely on that fact, there should never be an issue in practice.

If you're interested in revolving the theoretical issue with `Duration` and `FiniteDuration`, I think it should be enough to just swap their places. Did you try it?

File: core/src/main/scala/cats/Show.scala (hunk 2 above)
Comment (chwthewke) [reply core/src/main/scala/cats/Show.scala:121]: If I move catsShowForSortedSet back where it was in the Show companion object, I get an ambiguous implicit error on `ContravariantShow[BitSet]`

> [...]\cats\tests\shared\src\test\scala\cats\tests\ShowSuite.scala:92:15
> ambiguous implicit values:
>  both method catsShowForBitSet in object Show of type cats.Show[scala.collection.immutable.BitSet]
>  and method catsShowForSortedSet in object Show of type [A](implicit evidence$8: cats.Show[A]): cats.Show[scala.collection.immutable.SortedSet[A]]
>  match expected type cats.Show.ContravariantShow[scala.collection.immutable.BitSet]
>     implicitly[ContravariantShow[BitSet]]

Comment (joroKr21) [reply core/src/main/scala/cats/Show.scala:121]: Ah yes, `BitSet` is a subtype of `SortedSet`, good catch 👍

**Comment by chwthewke** [comment]
> If you're interested in resolving the theoretical issue with `Duration` and `FiniteDuration`, I think it should be enough to just swap their places. Did you try it?

That is exactly the first thing I tried, and it results in `ContravariantShow[Duration] eq ContravariantShow[FiniteDuration]` being true.

**Comment by joroKr21** [comment]
> That is exactly the first thing I tried, and it results in ContravariantShow[Duration] eq ContravariantShow[FiniteDuration] being true.

That's because it's the same lambda (`fromToString`) - LMF FTW

**Comment by chwthewke** [comment]
> > That is exactly the first thing I tried, and it results in ContravariantShow[Duration] eq ContravariantShow[FiniteDuration] being true.
> 
> That's because it's the same lambda (`fromToString`) - LMF FTW

Not sure what "LMF" means, but then I realized that `catsStdShowForDurationUnambiguous` and `catsStdShowForFiniteDurationUnambiguous` are **also** the same instance, and I have no idea why. In any case that means I don't think I want to change anything regarding `FiniteDuration`/`Duration`. (If there's only going to be a single `Show[Duration]` value - also serving as `Show[FiniteDuration]` - in a given JVM, nothing bad will ever happen).

All in all, I'd say I'm done here.

**Comment by joroKr21** [comment]
> Not sure what "LMF" means

LambdaMetafactory, used to implement lambdas on the JVM

**Review by satorg — APPROVED** [review]
Thanks!
