### PR TITLE
Fix many cats-kernel instances.

### LINKED ISSUE #1320: Move relevant function instances into kernel
Right now we have a `Monoid` for `Function1` values in *cats-core*. I think it makes sense to move the definition to *cats-kernel* since that's where monoids are defined -- this will allow *algebra* and other kernel-dependents to share these instances.

(More generally, I think where possible all orderings, monoids, etc. should live in *cats-kernel*.)

### PR DESCRIPTION
**Pull request by non**
This commit does a bunch of things:

 1. Move relevant either/function instnaces into kernel
 2. Add missing Eq/PartialOrder instances for Either
 3. Add many missing instances for Function0/Function1
 4. Add instances for BitSet
 5. Remove code duplication between collection monoids
 6. Improve test coverage of function instances
 7. Add some missing package objects in kernel
 8. A few stylistic changes

This is a relatively large commit but I think almost all of this is
stuff we'd like to get done before we freeze cats-kernel."

This fixes #1320.

### CODE REVIEW

**Comment by non** [comment]
(Another change I failed to mention was that I made several of the `Show` instances more efficient.)

**Comment by non** [comment]
Review by @johnynek, plus anyone else who is interested.

**Comment by non** [comment]
We may want to start using things `Helpers._` in our other tests -- it makes it a lot easier to be sure you're exercising all the different possible type class constructors.

**Comment by kailuowang** [comment]
👍  looks great to me. I wish we had that `Helper` before. Thanks!

File: core/src/main/scala/cats/instances/either.scala [hunk 1]
```diff
@@ -81,51 +81,19 @@ trait EitherInstances extends EitherInstances1 {
...
 
-private[instances] sealed trait EitherInstances1 extends EitherInstances2 {
-  implicit def catsStdPartialOrderForEither[A, B](implicit A: PartialOrder[A], B: PartialOrder[B]): PartialOrder[Either[A, B]] =
-    new PartialOrder[Either[A, B]] {
-      def partialCompare(x: Either[A, B], y: Either[A, B]): Double = x.fold(
-        a => y.fold(A.partialCompare(a, _), _ => -1),
-        b => y.fold(_ => 1, B.partialCompare(b, _))
+  implicit def catsStdShowForEither[A, B](implicit A: Show[A], B: Show[B]): Show[Either[A, B]] =
+    new Show[Either[A, B]] {
+      def show(f: Either[A, B]): String = f.fold(
```
Comment (johnynek) [inline core/src/main/scala/cats/instances/either.scala]: we have biased to `match` for alleged performance reasons. What do you think of it here?

File: core/src/main/scala/cats/instances/list.scala [hunk 2]
```diff
@@ -84,6 +84,7 @@ trait ListInstances extends cats.kernel.instances.ListInstances {
 
   implicit def catsStdShowForList[A:Show]: Show[List[A]] =
     new Show[List[A]] {
-      def show(fa: List[A]): String = fa.map(_.show).mkString("List(", ", ", ")")
+      def show(fa: List[A]): String =
+        fa.iterator.map(_.show).mkString("List(", ", ", ")")
```
Comment (johnynek) [inline core/src/main/scala/cats/instances/list.scala]: nice catch

File: core/src/main/scala/cats/instances/map.scala [hunk 3]
```diff
@@ -6,11 +6,11 @@ import scala.annotation.tailrec
...
   implicit def catsStdShowForMap[A, B](implicit showA: Show[A], showB: Show[B]): Show[Map[A, B]] =
-    Show.show[Map[A, B]] { m =>
-      val body = m.map { case (a, b) =>
-        s"${showA.show(a)} -> ${showB.show(b)})"
-      }.mkString(",")
-      s"Map($body)"
+    new Show[Map[A, B]] {
+      def show(m: Map[A, B]): String =
+        m.iterator
+          .map { case (a, b) => showA.show(a) + " -> " + showB.show(b) }
```
Comment (johnynek) [inline core/src/main/scala/cats/instances/map.scala]: why not `s"..."` here? Is + just as good? (compiled with a StringBuilder?)

File: kernel/src/main/scala/cats/kernel/instances/either.scala [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+            case Right(_) => -1
+          }
+          case Right(xx) => y match {
+            case Left(_) => 1
+            case Right(yy) => B.compare(xx, yy)
+          }
+        }
+    }
+
+  implicit def catsDataMonoidForEither[A, B](implicit B: Monoid[B]): Monoid[Either[A, B]] =
```
Comment (johnynek) [inline kernel/src/main/scala/cats/kernel/instances/either.scala]: still feel #1321 is an issue.

Comment (non) [inline kernel/src/main/scala/cats/kernel/instances/either.scala]: I thought of that but I didn't want to make this PR big *and* contentious.

File: core/src/main/scala/cats/instances/map.scala (hunk 3 above)
Comment (non) [inline core/src/main/scala/cats/instances/map.scala]: I thought the compiler would rewrite it to us a string builder, but maybe that's only Java? I can rewrite this using interpolation (it just ends up looking uglier IMO).

File: kernel/src/main/scala/cats/kernel/instances/either.scala (hunk 4 above)
Comment (johnynek) [inline kernel/src/main/scala/cats/kernel/instances/either.scala]: no semigroup here? I think we can have with `Semigroup[B]`.

File: core/src/main/scala/cats/instances/either.scala [hunk 5]
```diff
@@ -61,7 +61,7 @@ trait EitherInstances extends cats.kernel.instances.EitherInstances {
 
       def traverse[F[_], B, C](fa: Either[A, B])(f: B => F[C])(implicit F: Applicative[F]): F[Either[A, C]] =
         fa match {
-          case left @ Left(_) => F.pure(left)
+          case Left(a) => F.pure(Left(a))
```
Comment (johnynek) [inline core/src/main/scala/cats/instances/either.scala]: maybe: https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/either.scala#L301

```scala
case left @ Left(_) => F.pure(left.rightCast[C])
```
save an allocation?

File: core/src/main/scala/cats/instances/either.scala [hunk 6]
```diff
@@ -48,7 +48,7 @@ trait EitherInstances extends cats.kernel.instances.EitherInstances {
       @tailrec
       def tailRecM[B, C](b: B)(f: B => Either[A, Either[B, C]]): Either[A, C] =
         f(b) match {
-          case Left(a)         => Left(a)
+          case left @ Left(_)  => left.rightCast[C]
           case Right(Left(b1)) => tailRecM(b1)(f)
           case Right(Right(c)) => Right(c)
```
Comment (johnynek) [inline core/src/main/scala/cats/instances/either.scala]: `case Right(r) => r.leftCast[A]` should work, right?

**Comment by johnynek** [comment]
one last allocation to save, then I'm +1

**Comment by non** [comment]
@johnynek I think this is it right?

**Comment by johnynek** [comment]
👍 Thank you for this work!
