### PR TITLE
Fix unconventional package objects in kernel

### LINKED ISSUE #2781: unconventional package objects
we have several package objects that are not really package object since there is no corresponding packages and folders. Also their name is not conventional `package.scala` which throws warning in compiler. 
e.g. `kernel/instances/list`, `kernel/instances/tuple` etc. 
We can't make them normal objects now since that will break BC. But we should at least address the compiler warning and move those to `package.scala` and into corresponding folders. 
e.g. 
`kernel/instances/list.scala` -> `kernel/instances/list/package.scala`

### PR DESCRIPTION
**Pull request by denisrosca**
Closes #2781

### CODE REVIEW

File: kernel/src/main/scala/cats/kernel/instances/eq/package.scala [hunk 1]
```diff
@@ -1,6 +1,6 @@
 package cats.kernel
 package instances
 
-trait EqInstances extends EqToEquivConversion
+package object eq extends EqInstances
 
-object eq extends EqInstances
+trait EqInstances extends EqToEquivConversion
```
Comment (kailuowang) [inline kernel/src/main/scala/cats/kernel/instances/eq/package.scala]: not sure if this change is necessary

File: kernel/src/main/scala/cats/kernel/instances/hash/package.scala [hunk 2]
```diff
@@ -1,6 +1,6 @@
 package cats.kernel
 package instances
 
-trait HashInstances extends HashToHashingConversion
+package object hash extends HashInstances
 
-object hash extends HashInstances
+trait HashInstances extends HashToHashingConversion
```
Comment (kailuowang) [inline kernel/src/main/scala/cats/kernel/instances/hash/package.scala]: same here. the original is fine IMO

**Comment by kailuowang** [comment]
thanks so much! I think we should leave those existing non-package object alone.

**Comment by denisrosca** [comment]
I'll revert the changes breaking binary compatibility and keep the rest.

**Comment by denisrosca** [comment]
@kailuowang any idea what happened with the 2.12.7 build? It looks like it never actually completed.

**Comment by kailuowang** [comment]
Sometimes it hangs. I just restarted it, should be green soon
